version: 0.2

phases:
  install:
    commands:
      - echo Nothing to install...
  pre_build:
    commands:
      - echo Nothing to prebuild...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - **/*
